// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJhUHEiNIKZ_oSjphjmrvcRMYYr61O2c',
    appId: '1:78347985226:web:0bfdf4ac73d72dbb99e1b3',
    messagingSenderId: '78347985226',
    projectId: 'library-manager-5dd84',
    authDomain: 'library-manager-5dd84.firebaseapp.com',
    storageBucket: 'library-manager-5dd84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTYnX1DzQmak-9d3kic0EJzjdEbAAeorA',
    appId: '1:78347985226:android:0d82051d4875d3b099e1b3',
    messagingSenderId: '78347985226',
    projectId: 'library-manager-5dd84',
    storageBucket: 'library-manager-5dd84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVxQntbwzfB-kqhwXZEZ7Uelp8jLBbfM8',
    appId: '1:78347985226:ios:2441c8ed5e1593d399e1b3',
    messagingSenderId: '78347985226',
    projectId: 'library-manager-5dd84',
    storageBucket: 'library-manager-5dd84.appspot.com',
    iosBundleId: 'com.example.libraryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVxQntbwzfB-kqhwXZEZ7Uelp8jLBbfM8',
    appId: '1:78347985226:ios:eab7ce7ac70e939899e1b3',
    messagingSenderId: '78347985226',
    projectId: 'library-manager-5dd84',
    storageBucket: 'library-manager-5dd84.appspot.com',
    iosBundleId: 'com.example.libraryManagement.RunnerTests',
  );
}
